In [2]:
import pandas as pd

In [6]:
emp = pd.read_excel('employeee.xlsx')
#emp.isnull().sum() or emp.info()

In [20]:
emp.duplicated().any()

np.False_

In [18]:
emp = emp.drop_duplicates()
emp

   id     hiredate    sal   comm             job  record_year
0   1  01-jun-2000   5000    0.0         manager       2000.0
1   2   8-sep-2000   4000  400.0         analyst       2000.0
2   3  01-dec-2000   2000    NaN        salesman       2000.0
3   5  28-sep-2000   3000  100.0           clerk       2000.0
4   4   8-jan-2001   4000  200.0             NaN       2001.0
5   6   8-jan-2002  10000  100.0       president       2002.0
6   7   8-jan-2002   2000  250.0        salesman          NaN
7   9  18-feb-2002   7000  300.0       Developer       2002.0
8   8  12-feb-2002   9000  100.0  Data scientist       2002.0

In [ ]:
#handling the missing values
#handle using mean,meadian or mode or  drop the row
df.dropna(axis=0)  #this will remove all the rows which contains null valyes(nan)

In [32]:
comm_mean = emp['comm'].mean()
print(comm_mean)

181.25

In [34]:
job_mode = emp['job'].mode()[0]
print(job_mode)

salesman

In [31]:
rec_mode = emp['record_year'].mode()[0]
print(rec_mode)

2000.0

In [36]:
#replacing with fillna
emp['comm'] = emp['comm'].fillna(comm_mean)
emp['job'] = emp['job'].fillna(job_mode)
emp['record_year'] = emp['record_year'].fillna(rec_mode)

In [37]:
emp

   id     hiredate    sal    comm             job  record_year
0   1  01-jun-2000   5000    0.00         manager       2000.0
1   2   8-sep-2000   4000  400.00         analyst       2000.0
2   3  01-dec-2000   2000  181.25        salesman       2000.0
3   5  28-sep-2000   3000  100.00           clerk       2000.0
4   4   8-jan-2001   4000  200.00        salesman       2001.0
5   6   8-jan-2002  10000  100.00       president       2002.0
6   7   8-jan-2002   2000  250.00        salesman       2000.0
7   9  18-feb-2002   7000  300.00       Developer       2002.0
8   8  12-feb-2002   9000  100.00  Data scientist       2002.0

In [38]:
#hiredate , comm , record_year
emp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           9 non-null      int64
 1   hiredate     9 non-null      object
 2   sal          9 non-null      int64
 3   comm         9 non-null      float64
 4   job          9 non-null      object
 5   record_year  9 non-null      float64
dtypes: float64(2), int64(2), object(2)
memory usage: 504.0+ bytes

In [41]:
emp['hiredate'] = pd.to_datetime(emp['hiredate'])
emp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           9 non-null      int64
 1   hiredate     9 non-null      datetime64[ns]
 2   sal          9 non-null      int64
 3   comm         9 non-null      float64
 4   job          9 non-null      object
 5   record_year  9 non-null      float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(1)
memory usage: 504.0+ bytes

In [42]:
#coverting from float to int

emp = emp.astype({'comm':int,'record_year' : int})
emp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           9 non-null      int64
 1   hiredate     9 non-null      datetime64[ns]
 2   sal          9 non-null      int64
 3   comm         9 non-null      int64
 4   job          9 non-null      object
 5   record_year  9 non-null      int64
dtypes: datetime64[ns](1), int64(4), object(1)
memory usage: 504.0+ bytes