# Employee data analysis

In [33]:
import pandas as pd

In [34]:
df = pd.read_excel('employeee.xlsx')

In [35]:
print(df)

    id     hiredate    sal   comm             job  record_year
0    1  01-jun-2000   5000    0.0         manager       2000.0
1    2  08-sep-2000   4000  400.0         analyst       2000.0
2    3  01-dec-2000   2000    NaN        salesman       2000.0
3    5  28-sep-2000   3000  100.0           clerk       2000.0
4    4   8-jan-2001   4000  200.0             NaN       2001.0
5    6   8-jan-2002  10000  100.0       president       2002.0
6    7   8-jan-2002   2000  250.0        salesman          NaN
7    9  18-feb-2002   7000  300.0       Developer       2002.0
8    8  12-feb-2002   9000  100.0  Data scientist       2002.0
9    5  28-sep-2000   3000  100.0           clerk       2000.0
10   2   8-sep-2000   4000  400.0         analyst       2000.0

In [36]:
df.columns

Index(['id', 'hiredate', 'sal', 'comm', 'job', 'record_year'], dtype='object')

In [37]:
df.head()

   id     hiredate   sal   comm       job  record_year
0   1  01-jun-2000  5000    0.0   manager       2000.0
1   2  08-sep-2000  4000  400.0   analyst       2000.0
2   3  01-dec-2000  2000    NaN  salesman       2000.0
3   5  28-sep-2000  3000  100.0     clerk       2000.0
4   4   8-jan-2001  4000  200.0       NaN       2001.0

In [38]:
df.tail()

    id     hiredate   sal   comm             job  record_year
6    7   8-jan-2002  2000  250.0        salesman          NaN
7    9  18-feb-2002  7000  300.0       Developer       2002.0
8    8  12-feb-2002  9000  100.0  Data scientist       2002.0
9    5  28-sep-2000  3000  100.0           clerk       2000.0
10   2   8-sep-2000  4000  400.0         analyst       2000.0

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           11 non-null     int64
 1   hiredate     11 non-null     object
 2   sal          11 non-null     int64
 3   comm         10 non-null     float64
 4   job          10 non-null     object
 5   record_year  10 non-null     float64
dtypes: float64(2), int64(2), object(2)
memory usage: 660.0+ bytes

In [40]:
df.describe()

              id           sal        comm  record_year
count  11.000000     11.000000   10.000000    10.000000
mean    4.727273   4818.181818  195.000000  2000.700000
std     2.611165   2713.602101  138.343373     0.948683
min     1.000000   2000.000000    0.000000  2000.000000
25%     2.500000   3000.000000  100.000000  2000.000000
50%     5.000000   4000.000000  150.000000  2000.000000
75%     6.500000   6000.000000  287.500000  2001.750000
max     9.000000  10000.000000  400.000000  2002.000000

In [41]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
dtype: bool

## Data cleaning

1) check for duplicates
2) check for missing values and handle them
3) check for invalid dtype and handle them
4) remove the unwanted columns

In [ ]:
#practice data cleaning with a lots of data using pandas