# importing the required libraries

In [5]:
import pandas as pd

In [6]:
df=pd.read_csv('movies.csv')

In [7]:
df.info()
df.duplicated().any()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16744 entries, 0 to 16743
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       16744 non-null  int64
 1   ID               16744 non-null  int64
 2   Title            16744 non-null  object
 3   Year             16744 non-null  int64
 4   Age              7354 non-null   object
 5   IMDb             16173 non-null  float64
 6   Rotten Tomatoes  5158 non-null   object
 7   Netflix          16744 non-null  int64
 8   Hulu             16744 non-null  int64
 9   Prime Video      16744 non-null  int64
 10  Disney+          16744 non-null  int64
 11  Type             16744 non-null  int64
 12  Directors        16018 non-null  object
 13  Genres           16469 non-null  object
 14  Country          16309 non-null  object
 15  Language         16130 non-null  object
 16  Runtime          16152 non-null  float64
dtypes: float64(2), int64(8), object(7)
memory usage: 2.2+ MB

,Unnamed: 0,ID,Title,Year,Age,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+,Type,Directors,Genres,Country,Language,Runtime
0,0,1,Inception,2010,13+,8.8,87%,1,0,0,0,0,Christopher Nolan,"Action,Adventure,Sci-Fi,Thriller","United States,United Kingdom","English,Japanese,French",148.0
1,1,2,The Matrix,1999,18+,8.7,87%,1,0,0,0,0,"Lana Wachowski,Lilly Wachowski","Action,Sci-Fi",United States,English,136.0
2,2,3,Avengers: Infinity War,2018,13+,8.5,84%,1,0,0,0,0,"Anthony Russo,Joe Russo","Action,Adventure,Sci-Fi",United States,English,149.0
3,3,4,Back to the Future,1985,7+,8.5,96%,1,0,0,0,0,Robert Zemeckis,"Adventure,Comedy,Sci-Fi",United States,English,116.0
4,4,5,"The Good, the Bad and the Ugly",1966,18+,8.8,97%,1,0,1,0,0,Sergio Leone,Western,"Italy,Spain,West Germany",Italian,161.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16739,16739,16740,The Ghosts of Buxley Hall,1980,NaN,6.2,NaN,0,0,0,1,0,Bruce Bilson,"Comedy,Family,Fantasy,Horror",United States,English,120.0
16740,16740,16741,The Poof Point,2001,7+,4.7,NaN,0,0,0,1,0,Neal Israel,"Comedy,Family,Sci-Fi",United States,English,90.0
16741,16741,16742,Sharks of Lost Island,2013,NaN,5.7,NaN,0,0,0,1,0,Neil Gelinas,Documentary,United States,English,NaN
16742,16742,16743,Man Among Cheetahs,2017,NaN,6.6,NaN,0,0,0,1,0,Richard Slater-Jones,Documentary,United States,English,NaN
16743,16743,16744,In Beaver Valley,1950,NaN,NaN,NaN,0,0,0,1,0,James Algar,"Documentary,Short,Family",United States,English,32.0

In [8]:
df['Age']=df['Age'].fillna(df['Age'].mode()[0])
df['Rotten Tomatoes']=df['Rotten Tomatoes'].fillna(df['Rotten Tomatoes'].mode()[0])
df['IMDb']=df['IMDb'].fillna(df['IMDb'].mean()).round(1)
df['Runtime']=df['Runtime'].fillna(df['Runtime']).mean().round(1)

for i in ['Directors','Genres','Country','Language']:
    df[i]=df[i].fillna('Unknown')
df.info()

df['Rotten Tomatoes']=(df['Rotten Tomatoes'].str.strip('%').astype(float)/10).round(1)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16744 entries, 0 to 16743
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       16744 non-null  int64
 1   ID               16744 non-null  int64
 2   Title            16744 non-null  object
 3   Year             16744 non-null  int64
 4   Age              16744 non-null  object
 5   IMDb             16744 non-null  float64
 6   Rotten Tomatoes  16744 non-null  object
 7   Netflix          16744 non-null  int64
 8   Hulu             16744 non-null  int64
 9   Prime Video      16744 non-null  int64
 10  Disney+          16744 non-null  int64
 11  Type             16744 non-null  int64
 12  Directors        16744 non-null  object
 13  Genres           16744 non-null  object
 14  Country          16744 non-null  object
 15  Language         16744 non-null  object
 16  Runtime          16744 non-null  float64
dtypes: float64(2), int64(8), object(7)
memory usage: 2.2+ MB

In [9]:
df

,Unnamed: 0,ID,Title,Year,Age,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+,Type,Directors,Genres,Country,Language,Runtime
0,0,1,Inception,2010,13+,8.8,8.7,1,0,0,0,0,Christopher Nolan,"Action,Adventure,Sci-Fi,Thriller","United States,United Kingdom","English,Japanese,French",93.4
1,1,2,The Matrix,1999,18+,8.7,8.7,1,0,0,0,0,"Lana Wachowski,Lilly Wachowski","Action,Sci-Fi",United States,English,93.4
2,2,3,Avengers: Infinity War,2018,13+,8.5,8.4,1,0,0,0,0,"Anthony Russo,Joe Russo","Action,Adventure,Sci-Fi",United States,English,93.4
3,3,4,Back to the Future,1985,7+,8.5,9.6,1,0,0,0,0,Robert Zemeckis,"Adventure,Comedy,Sci-Fi",United States,English,93.4
4,4,5,"The Good, the Bad and the Ugly",1966,18+,8.8,9.7,1,0,1,0,0,Sergio Leone,Western,"Italy,Spain,West Germany",Italian,93.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16739,16739,16740,The Ghosts of Buxley Hall,1980,18+,6.2,10.0,0,0,0,1,0,Bruce Bilson,"Comedy,Family,Fantasy,Horror",United States,English,93.4
16740,16740,16741,The Poof Point,2001,7+,4.7,10.0,0,0,0,1,0,Neal Israel,"Comedy,Family,Sci-Fi",United States,English,93.4
16741,16741,16742,Sharks of Lost Island,2013,18+,5.7,10.0,0,0,0,1,0,Neil Gelinas,Documentary,United States,English,93.4
16742,16742,16743,Man Among Cheetahs,2017,18+,6.6,10.0,0,0,0,1,0,Richard Slater-Jones,Documentary,United States,English,93.4
16743,16743,16744,In Beaver Valley,1950,18+,5.9,10.0,0,0,0,1,0,James Algar,"Documentary,Short,Family",United States,English,93.4

# Data transfomation / Feature engineering

In [10]:
plts_df=pd.melt(df,id_vars=['Title','IMDb','Rotten Tomatoes'],value_vars=['Netflix',	'Hulu',	'Prime Video',	'Disney+'],var_name='platforms',value_name='Availability')

In [11]:
plts_df=plts_df.loc[plts_df['Availability']==1]

In [12]:
plts_df=plts_df.drop(columns=['Availability'])

In [13]:
df['tot_plt']=df[['Netflix', 'Hulu', 'Prime Video', 'Disney+']].sum(axis=1)

# Data Analysis

1. Find the no.of movies available in the dataset

In [14]:
df.shape[0]
#or
len(df)
#or
df['Title'].count()

16744

2.Find the total movies which are casted in netflix

In [15]:
df['Netflix'].sum()
#or
df.loc[df['Netflix']==1 ,'Netflix'].count()
#or
df.loc[df['Netflix']==1 ,'Netflix'].shape[0]
#or
df.query('Netflix==1').shape[0]

3560

3.get the platform wise no.of movies

In [16]:
df[[ 'Netflix', 'Hulu', 'Prime Video', 'Disney+']].sum()
#or
plts_df['platforms'].value_counts()          # this is the melted data

platforms
Prime Video    12354
Netflix         3560
Hulu             903
Disney+          564
Name: count, dtype: int64

4.get the platform imdb and rotten tomatoes rating

In [17]:
plts_df.groupby('platforms').agg({'IMDb':'mean','Rotten Tomatoes':'mean'}).round(1)

             IMDb  Rotten Tomatoes
platforms
Disney+       6.4              7.8
Hulu          6.1              7.7
Netflix       6.2              8.6
Prime Video   5.8              9.1

In [18]:
#pivot() and pivot_table
df

,Unnamed: 0,ID,Title,Year,Age,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+,Type,Directors,Genres,Country,Language,Runtime,tot_plt
0,0,1,Inception,2010,13+,8.8,8.7,1,0,0,0,0,Christopher Nolan,"Action,Adventure,Sci-Fi,Thriller","United States,United Kingdom","English,Japanese,French",93.4,1
1,1,2,The Matrix,1999,18+,8.7,8.7,1,0,0,0,0,"Lana Wachowski,Lilly Wachowski","Action,Sci-Fi",United States,English,93.4,1
2,2,3,Avengers: Infinity War,2018,13+,8.5,8.4,1,0,0,0,0,"Anthony Russo,Joe Russo","Action,Adventure,Sci-Fi",United States,English,93.4,1
3,3,4,Back to the Future,1985,7+,8.5,9.6,1,0,0,0,0,Robert Zemeckis,"Adventure,Comedy,Sci-Fi",United States,English,93.4,1
4,4,5,"The Good, the Bad and the Ugly",1966,18+,8.8,9.7,1,0,1,0,0,Sergio Leone,Western,"Italy,Spain,West Germany",Italian,93.4,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16739,16739,16740,The Ghosts of Buxley Hall,1980,18+,6.2,10.0,0,0,0,1,0,Bruce Bilson,"Comedy,Family,Fantasy,Horror",United States,English,93.4,1
16740,16740,16741,The Poof Point,2001,7+,4.7,10.0,0,0,0,1,0,Neal Israel,"Comedy,Family,Sci-Fi",United States,English,93.4,1
16741,16741,16742,Sharks of Lost Island,2013,18+,5.7,10.0,0,0,0,1,0,Neil Gelinas,Documentary,United States,English,93.4,1
16742,16742,16743,Man Among Cheetahs,2017,18+,6.6,10.0,0,0,0,1,0,Richard Slater-Jones,Documentary,United States,English,93.4,1
16743,16743,16744,In Beaver Valley,1950,18+,5.9,10.0,0,0,0,1,0,James Algar,"Documentary,Short,Family",United States,English,93.4,1