# 1) Importing the Libraries

In [53]:
import pandas as pd
import numpy as np

# 2) Loading the Dataset

In [54]:
tit = pd.read_csv('titanic.csv')
tit

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

# 3) Understanding the Data

In [55]:
tit.columns

Index(['pclass', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket', 'fare',
       'cabin', 'embarked', 'survived'],
      dtype='object')

##### passenger --> this is just a generated ID
##### p class --> which class did the passenger ride
##### name -- > self explanatory
##### sex -- > gender
##### age --> s e
##### sibsp --> were the passengers spouse or siblings with them on the ship
##### parch --> were the passengers parents or childern with them on the ship
##### ticket --> ticket number
##### fare --> ticket price
##### cabin --> 
##### embarked 
##### survived

In [56]:
tit.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0

In [57]:
tit.dtypes

pclass        int64
name         object
sex          object
age         float64
sibsp         int64
parch         int64
ticket       object
fare        float64
cabin        object
embarked     object
survived      int64
dtype: object

In [58]:
tit.tail()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
1304,3,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0,0,0,315082,7.8750,NaN,S,0

In [59]:
tit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pclass    1309 non-null   int64
 1   name      1309 non-null   object
 2   sex       1309 non-null   object
 3   age       1046 non-null   float64
 4   sibsp     1309 non-null   int64
 5   parch     1309 non-null   int64
 6   ticket    1309 non-null   object
 7   fare      1308 non-null   float64
 8   cabin     295 non-null    object
 9   embarked  1307 non-null   object
 10  survived  1309 non-null   int64
dtypes: float64(2), int64(4), object(5)
memory usage: 112.6+ KB

In [60]:
tit['survived'].value_counts()

survived
0    809
1    500
Name: count, dtype: int64

In [61]:
tit['sex'].value_counts()

sex
male      843
female    466
Name: count, dtype: int64

In [62]:
tit['pclass'].value_counts()

pclass
3    709
1    323
2    277
Name: count, dtype: int64

In [63]:
#percentage who survived
per = np.mean(tit['survived'][tit['sex']=='male']) 
print(per*100)

19.098457888493474

In [64]:
tit.shape

(1309, 11)

### Note down invalid datatypes,handle the missing values

# 4) Data Cleaning

# Observation
1.No duplicates

2.null values present 
 
        1.age:float-> (mean)

        2.fare:float-> (mean)

        3.cabin:object-> (remove the column as it is not important for stating wheter the passenger survied or not)
  
        4.embarked:object->(mode)

3.No invalid datatype

##### Check for Duplicate Values
##### Replace with Mean,Mode,Median
##### astype(),to_datetime()

In [65]:
#there are no duplicate values
tit.duplicated().any()

False

In [66]:
tit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pclass    1309 non-null   int64
 1   name      1309 non-null   object
 2   sex       1309 non-null   object
 3   age       1046 non-null   float64
 4   sibsp     1309 non-null   int64
 5   parch     1309 non-null   int64
 6   ticket    1309 non-null   object
 7   fare      1308 non-null   float64
 8   cabin     295 non-null    object
 9   embarked  1307 non-null   object
 10  survived  1309 non-null   int64
dtypes: float64(2), int64(4), object(5)
memory usage: 112.6+ KB

In [67]:
age_mean = tit['age'].mean()
fare_mean=tit['fare'].mean()
emb_mode=tit['embarked'].mode()[0]
tit['age']=tit['age'].fillna(age_mean)   #replacing null values with mean
tit['fare']=tit['fare'].fillna(fare_mean)  #replacing null values with mean
tit['embarked']=tit['embarked'].fillna(emb_mode)  #replacing null values with mode
tit=tit.drop(columns=['cabin'])
tit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pclass    1309 non-null   int64
 1   name      1309 non-null   object
 2   sex       1309 non-null   object
 3   age       1309 non-null   float64
 4   sibsp     1309 non-null   int64
 5   parch     1309 non-null   int64
 6   ticket    1309 non-null   object
 7   fare      1309 non-null   float64
 8   embarked  1309 non-null   object
 9   survived  1309 non-null   int64
dtypes: float64(2), int64(4), object(4)
memory usage: 102.4+ KB

# 5) Data Transformation / Feature Engineering

In [68]:
tit['age'] = tit['age'].round(1)
tit['fare'] = tit['fare'].round(1)
tit.head(3)

,pclass,name,sex,age,sibsp,parch,ticket,fare,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0,0,0,24160,211.3,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9,1,2,113781,151.6,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0,1,2,113781,151.6,S,0

In [69]:
#renaming 
tit = tit.rename(columns = {'sex':'Gender'})
tit.head()

,pclass,name,Gender,age,sibsp,parch,ticket,fare,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0,0,0,24160,211.3,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9,1,2,113781,151.6,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0,1,2,113781,151.6,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0,1,2,113781,151.6,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0,1,2,113781,151.6,S,0

In [70]:
#title case that is first letter capital and remaining lower case
tit['Gender']=tit['Gender'].str.title()
tit

,pclass,name,Gender,age,sibsp,parch,ticket,fare,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",Female,29.0,0,0,24160,211.3,S,1
1,1,"Allison, Master. Hudson Trevor",Male,0.9,1,2,113781,151.6,S,1
2,1,"Allison, Miss. Helen Loraine",Female,2.0,1,2,113781,151.6,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",Male,30.0,1,2,113781,151.6,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",Female,25.0,1,2,113781,151.6,S,0
...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",Female,14.5,1,0,2665,14.5,C,0
1305,3,"Zabour, Miss. Thamine",Female,29.9,1,0,2665,14.5,C,0
1306,3,"Zakarian, Mr. Mapriededer",Male,26.5,0,0,2656,7.2,C,0
1307,3,"Zakarian, Mr. Ortin",Male,27.0,0,0,2670,7.2,C,0
1308,3,"Zimmerman, Mr. Leo",Male,29.0,0,0,315082,7.9,S,0

# Data Analysis

### 1. get all the passenger details

In [71]:
tit

,pclass,name,Gender,age,sibsp,parch,ticket,fare,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",Female,29.0,0,0,24160,211.3,S,1
1,1,"Allison, Master. Hudson Trevor",Male,0.9,1,2,113781,151.6,S,1
2,1,"Allison, Miss. Helen Loraine",Female,2.0,1,2,113781,151.6,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",Male,30.0,1,2,113781,151.6,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",Female,25.0,1,2,113781,151.6,S,0
...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",Female,14.5,1,0,2665,14.5,C,0
1305,3,"Zabour, Miss. Thamine",Female,29.9,1,0,2665,14.5,C,0
1306,3,"Zakarian, Mr. Mapriededer",Male,26.5,0,0,2656,7.2,C,0
1307,3,"Zakarian, Mr. Ortin",Male,27.0,0,0,2670,7.2,C,0
1308,3,"Zimmerman, Mr. Leo",Male,29.0,0,0,315082,7.9,S,0

#### 2.Get all the passengers name(full name)

In [72]:
tit['first_name']+' '+tit['last_name']

KeyError: 'first_name'

### 3. get all the passengers name,age and gender

### 4.get male passengers details

In [ ]:
tit.query("gender=='Male'")
tit.loc[tit['gender']=='Male']

UndefinedVariableError: name 'gender' is not defined

### 5. Get Female Passengers name and passengers class

In [ ]:
tit.loc[tit['gender']=='Female',['f_name','pclass']]
tit.query("gender == 'Female'")[['f_name','plclass']]

KeyError: 'gender'

### 6. get Male passengers details  who are traveliing with pclass1

In [ ]:
tit.query("gender == 'Male' and pclass==1")
#or
tit.loc[(tit["gender"]=='Male') & (tit["pclass"] == 1),]

### 7. get femsthe passenger details who are taravelljf eo