In [16]:
import pandas as pd

In [17]:
df = pd.DataFrame({
    'Product':['A','B','C','A','B','C'],
    'Month':['JAN','JAN','JAN','FEB','FEB','FEB'],
    'Qunatity_sold':[100,120,95,110,130,100],
    'Revenue':[5000,6000,4500,5500,7000,4800]
})

In [18]:
#this is just for my understanding
# df = pd.DataFrame({
#     'Product':['A','B','C','A','B','C','C'],#C acts as a duplicate
#     'Month':['JAN','JAN','JAN','FEB','FEB','FEB','FEB'], #Feb acts as a Duplicate
#     'Qunatity_sold':[100,120,95,110,130,100,110],
#     'Revenue':[5000,6000,4500,5500,7000,4800,5000]
# })

In [19]:
df

  Product Month  Qunatity_sold  Revenue
0       A   JAN            100     5000
1       B   JAN            120     6000
2       C   JAN             95     4500
3       A   FEB            110     5500
4       B   FEB            130     7000
5       C   FEB            100     4800

### Product will become Rows and Months Will become Columns

In [20]:
df.pivot(index = 'Product',columns = 'Month')

        Qunatity_sold      Revenue
Month             FEB  JAN     FEB   JAN
Product
A                 110  100    5500  5000
B                 130  120    7000  6000
C                 100   95    4800  4500

In [21]:
df.pivot(index = 'Product',columns = 'Month',values = 'Revenue')

Month     FEB   JAN
Product
A        5500  5000
B        7000  6000
C        4800  4500

### Aggregation functions usually return floats to maintain precision

In [22]:
df.pivot_table(index = 'Product',columns = 'Month')

        Qunatity_sold        Revenue
Month             FEB    JAN     FEB     JAN
Product
A               110.0  100.0  5500.0  5000.0
B               130.0  120.0  7000.0  6000.0
C               100.0   95.0  4800.0  4500.0

### checking with duplicate values

In [23]:
df = pd.DataFrame({
    'Product':['A','B','C','A','B','C','C'],#C acts as a duplicate
    'Month':['JAN','JAN','JAN','FEB','FEB','FEB','FEB'], #Feb acts as a Duplicate
    'Qunatity_sold':[100,120,95,110,130,100,110],
    'Revenue':[5000,6000,4500,5500,7000,4800,5000]
})

In [24]:
df

  Product Month  Qunatity_sold  Revenue
0       A   JAN            100     5000
1       B   JAN            120     6000
2       C   JAN             95     4500
3       A   FEB            110     5500
4       B   FEB            130     7000
5       C   FEB            100     4800
6       C   FEB            110     5000

### here it will take the mean value (aggregation) whenever there is a duplicate

In [25]:
df.pivot_table(index = 'Product',columns = 'Month')

        Qunatity_sold        Revenue
Month             FEB    JAN     FEB     JAN
Product
A               110.0  100.0  5500.0  5000.0
B               130.0  120.0  7000.0  6000.0
C               105.0   95.0  4900.0  4500.0

In [26]:
df.pivot_table(index = 'Product',columns = 'Month',aggfunc= sum )

C:\Users\pushp\AppData\Local\Temp\ipykernel_31972\3459062136.py:1: FutureWarning: The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.pivot_table(index = 'Product',columns = 'Month',aggfunc= sum )

        Qunatity_sold      Revenue
Month             FEB  JAN     FEB   JAN
Product
A                 110  100    5500  5000
B                 130  120    7000  6000
C                 210   95    9800  4500

In [28]:
df.pivot_table(index = 'Product',columns = 'Month',aggfunc= 'sum', margins = True)

        Qunatity_sold           Revenue
Month             FEB  JAN  All     FEB    JAN    All
Product
A                 110  100  210    5500   5000  10500
B                 130  120  250    7000   6000  13000
C                 210   95  305    9800   4500  14300
All               450  315  765   22300  15500  37800