In [213]:
import pandas as pd

In [214]:
df = pd.read_csv('weather.csv')

In [215]:
df

       date      city  temperature  humidity
0  5/1/2017  new york           65        56
1  5/2/2017  new york           66        58
2  5/3/2017  new york           68        60
3  5/1/2017    mumbai           75        80
4  5/2/2017    mumbai           78        83
5  5/3/2017    mumbai           82        85
6  5/1/2017   beijing           80        26
7  5/2/2017   beijing           77        30
8  5/3/2017   beijing           79        35

### Pivot is used to reshape or transform the data

In [216]:
df.pivot(index = 'date',columns = 'city')

         temperature                 humidity
city         beijing mumbai new york  beijing mumbai new york
date
5/1/2017          80     75       65       26     80       56
5/2/2017          77     78       66       30     83       58
5/3/2017          79     82       68       35     85       60

In [217]:
df.pivot(index = 'date',columns = 'city',values = 'humidity')

city      beijing  mumbai  new york
date
5/1/2017       26      80        56
5/2/2017       30      83        58
5/3/2017       35      85        60

In [218]:
df.pivot(index = 'humidity',columns = 'city')

              date                     temperature
city       beijing    mumbai  new york     beijing mumbai new york
humidity
26        5/1/2017       NaN       NaN        80.0    NaN      NaN
30        5/2/2017       NaN       NaN        77.0    NaN      NaN
35        5/3/2017       NaN       NaN        79.0    NaN      NaN
56             NaN       NaN  5/1/2017         NaN    NaN     65.0
58             NaN       NaN  5/2/2017         NaN    NaN     66.0
60             NaN       NaN  5/3/2017         NaN    NaN     68.0
80             NaN  5/1/2017       NaN         NaN   75.0      NaN
83             NaN  5/2/2017       NaN         NaN   78.0      NaN
85             NaN  5/3/2017       NaN         NaN   82.0      NaN

### Pivot Table is used to summarize and aggregate data inside dataframe

In [219]:
df = pd.read_csv('weather.csv')
df

       date      city  temperature  humidity
0  5/1/2017  new york           65        56
1  5/2/2017  new york           66        58
2  5/3/2017  new york           68        60
3  5/1/2017    mumbai           75        80
4  5/2/2017    mumbai           78        83
5  5/3/2017    mumbai           82        85
6  5/1/2017   beijing           80        26
7  5/2/2017   beijing           77        30
8  5/3/2017   beijing           79        35

### Default aggregation is mean (but here each value is unique, so mean = actual value)

In [220]:
df.pivot_table(index = "date", columns = "city")

         humidity                 temperature
city      beijing mumbai new york     beijing mumbai new york
date
5/1/2017     26.0   80.0     56.0        80.0   75.0     65.0
5/2/2017     30.0   83.0     58.0        77.0   78.0     66.0
5/3/2017     35.0   85.0     60.0        79.0   82.0     68.0

In [221]:
df.pivot_table(index = 'city',columns = 'date',aggfunc="sum")

         humidity                   temperature
date     5/1/2017 5/2/2017 5/3/2017    5/1/2017 5/2/2017 5/3/2017
city
beijing        26       30       35          80       77       79
mumbai         80       83       85          75       78       82
new york       56       58       60          65       66       68

In [ ]:
df.pivot_table(index = 'city',columns = 'date',aggfunc="diff")
#without assigning why this is not producing the output

Empty DataFrame
Columns: []
Index: []